Implement DeRegister for graceful party shutdown
eigengravy/tinyfl pull request #15
Opened 2023-06-07 06:37 UTC by Ceres445

Closes #5 

> De-register party from aggregator and graceful shutdown.
> 
> * [x]  Implement De-register message dataclass.
> * [x]  Send de-register request to aggregator when a party is shutting down.
> * [x]  Handle de-register message on the aggregator to remove party from client set.

2023-06-07 06:38 UTC, Ceres445 commented
Doesn't work on [docker](https://github.com/encode/uvicorn/issues/1215) containers .

I'm checking if there is a workaround

2023-06-07 07:04 UTC, Ceres445 commented
Works for docker containers now

2023-06-07 13:46 UTC, eigengravy requested changes

2023-06-07 13:46 UTC, eigengravy commented on tinyfl/aggregator/__init__.py
> +            logger.info("Client registered")
log the client's url as well
```suggestion
            logger.info(f"Client {url} registered")
```

2023-06-07 13:46 UTC, eigengravy commented on tinyfl/aggregator/__init__.py
> +            logger.info("Client de-registered")
same as above
```suggestion
            logger.info(f"Client {url} de-registered")
```

2023-06-08 12:55 UTC, eigengravy approved these changes
lgtm

2023-06-08 12:55 UTC, merged